### ISSUE TITLE
[Feature]: Get the % of entities synced when using torii-client

### ISSUE THREAD

**Issue by aymericdelab** [dojoengine/dojo.js#100]
### Feature Request

As the number of entities in the world get bigger and bigger, syncing of the torii-client takes more and more time.
Would be a nice addition for UX to know what is the progress of the syncing.

### Proposed Solution

i'm thinking we could make a simple API call to the remote torii to get total number of entities and compare that to the number of entities currently synced.

### If the feature is accepted, would you be willing to contribute it?

- [ ] Yes I would be willing to contribute

**Comment by tarrencev** [comment]
Great idea. I think this is already exposed with the graphql api right? In the pagination info? The request here is to add it for the grpc?

**Comment by broody** [comment]
Tracking issue here: https://github.com/dojoengine/dojo/issues/1423

**Comment by aymericdelab** [comment]
awesome, thank you !

**Comment by ponderingdemocritus** [comment]
being worked on in core closing
