### ISSUE TITLE
[Enhancement]: Add Threejs Starter

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#111]
### Feedback

Threejs is a fantastic graphics library and is perfect for grid based games.

This task it to finish a Threejs starter

It will include
- Vite
- Threejs
- Recs for torii state
- Zustand for Client UI state
- Threejs grid component
- VIte PWA

### If the request is accepted, would you be willing to contribute it?

- [ ] Yes I would be willing to contribute

**Comment by caillef** [comment]
I started working on that, I will link the repo here soon.
