### ISSUE TITLE
[Bug]: torii.createClient() on Safari and Firefox

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo.js#130]
### Dojo.js Version

0.5.0

### What happened?

The torii wasm client on Safari and Firefox takes 60+ seconds to start, or never starts.
On the react-app example, it never returns, freezing the app.

https://github.com/dojoengine/dojo.js/blob/bc3ca835c0508b7f6dc5315a8c1bba1c1abc80da/examples/react/react-app/src/dojo/generated/setup.ts#L16

### What is the expected behavior?

The torii wasm client should start quickly, as in Chrome and Chromium.

### Steps to reproduce

* Bootstrap the react-app example with dojo-starter
* start katana, migrate, start torii, start client
* open the client on Safari and Firefox: `torii.createClient()` never returns, freezing the app before it starts
 
or use on our current deployment, it takes 60+ seconds to start the tori client on Safari, and it never starts on Firefox:
[https://pistols.lootunder.world/gate](https://pistols.lootunder.world/gate)

Tested on macOS 13 and 14
Safari 17.0
Firefox 122.0

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by Larkooo** [comment]
It seems like the SubscribeModels gRPC request what's causing the blocking. Will investigate

**Comment by Larkooo** [comment]
It might be an issue with wasm-bindgen-futures or the grpc client on wasm. It seems that every stream seems to be blocking on WASM

**Comment by Larkooo** [comment]
Ok so I've done some more digging and it seems like the issue is actually maybe related to CORS..? Maybe firefox and safari are more strict on CORS than chrome which is why it fails. What's weird tho is that it only displays the CORS issue sometimes and sometimes fails silently and prints other error messages (due to the request maybe failing?)
