### ISSUE TITLE
[Feature]: React Native Starter

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#147]
A very simple React Native Starter based off the dojo-starter repo.

**Comment by Mohiiit** [comment]
Hey, can I work on this?

**Comment by ayushtom** [comment]
Can i pick this? @ponderingdemocritus

**Comment by ugur-eren** [comment]
Would this be an example project similar to [react-app example](https://github.com/dojoengine/dojo.js/tree/main/examples/react/react-app)
Or a whole new starter repo similar to [dojo-starter repo](https://github.com/dojoengine/dojo-starter)

**Comment by Xaxxoo** [comment]
Hi @ponderingdemocritus, I am still checking up on this issue.

**Comment by ayushtom** [comment]
i am taking this up

**Comment by ayushtom** [comment]
I can take this up.

**Comment by LamsyA** [comment]
Hello @ponderingdemocritus, Kindly Assign this to me
 I will create the basic Components. 
 I am confident that I can deliver a high-quality React Native starter template based on the `dojo-starter` repo.
