### ISSUE TITLE
[Feature]: Expo Starter

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#148]
Create a React Expo starter - https://expo.dev/

**Comment by ponderingdemocritus** [comment]
done!

**Comment by ugur-eren** [comment]
Hi @ponderingdemocritus Can I please take this and React Native issues?
I'm aware that some of the currently implemented hooks will need change to work with both React Native and Browser environments, and I think I can achieve it.

**Comment by satyambnsal** [comment]
@ugur-eren @ponderingdemocritus I've implemented the similar example for expo that we are using in react. Planning to commit my code today 😅. 
Sorry I should have updated the status here long before.

**Comment by satyambnsal** [comment]
https://github.com/satyambnsal/expo-basic-game

**Comment by ponderingdemocritus** [comment]
@satyambnsal will you be able to PR your example soon?
