### ISSUE TITLE
[Bug]: Enum are received as NaN

### ISSUE THREAD

**Issue by caillef** [dojoengine/dojo.js#151]
### Dojo.js Version

0.5.1

### What happened?

Here is my component generated by the script.
There are 3 enums in customTypes
```cairo
Machine: (() => {
      return defineComponent(
        world,
        { id: RecsType.Number, x: RecsType.Number, y: RecsType.Number, machine_type: RecsType.Number, direction: RecsType.Number, source: RecsType.Number, source_dist: RecsType.Number, resource_type: RecsType.Number, placed_at: RecsType.Number, last_compute_at: RecsType.Number },
        {
          metadata: {
            name: "Machine",
            types: ["u32","u32","u32","enum","enum","u32","u32","enum","u64","u64"],
            customTypes: ["MachineType","Direction","ResourceType"],
          },
        }
      );
    })(),
```

here is how I retrieve the machines
```js
useEffect(() => {
        defineSystem(world, [Has(Machine)], ({ value: [newValue] }: any) => {
            console.log(newValue)
        });
    }, []);
```

But newValue looks like this:
```js
{
direction: NaN, -- customType
id: 1,
last_compute_at: 1708666803,
machine_type: NaN, -- customType
placed_at: 1708666803,
resource_type: NaN, -- customType
source: 0,
source_dist: 0,
x: 1000,
y: 1000
}
```

And here is my enum definition
```rust
#[derive(Serde, Copy, Drop, Introspect, PartialEq, Eq)]
enum ResourceType {
    None,
    IronOre,
    IronIngot,
    IronPlate,
}
```

I tried without defineSystem but with this and I have the same issue
```js
const machine = useComponentValue(MachineClientComponent, props.machineId);
console.log(machine)
```

### What is the expected behavior?

Not sure if it should at least return a number value, or directly the right enum (they are not generated right now, maybe we need a new generated file with all the enums?)

### Steps to reproduce

Using the dojo-starter + threejs example, I sometimes have a number value when I print "last_direction", but most of the time it's NaN. Maybe it's because of the override.
The issue seems to be that @dojoengine/recs is never using the customTypes value, at least I can't see where it is used.

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by ktarun1419** [comment]
Hello, @caillef , may I take on this issue?

**Comment by rsodre** [comment]
I noticed this behavior before and have since used `u8` instead of enums. Was wondering it it was working or not.

Those puer enums don't really have any value attached to them.
Does it make any difference if you initialize the enum members with numbers, like this?

```rust
#[derive(Serde, Copy, Drop, Introspect, PartialEq, Eq)]
enum ResourceType {
    None = 0_u8,
    IronOre = 1_u8,
    IronIngot = 2_u8,
    IronPlate = 3_u8,
```
