### ISSUE TITLE
[Bug]: Failed in running `pnpm create-components` in version 0.5.11-alpha.0

### ISSUE THREAD

**Issue by LidamaoHub** [dojoengine/dojo.js#158]
### Dojo.js Version

0.5.11-alpha.0 

### What happened?

wen the `pnpm create-components` command run in 0.5.0 it works, but when run it in @dojoengine/core@0.5.11-alpha.0 the command line will report an error, both command run in the same environment
![image](https://github.com/dojoengine/dojo.js/assets/6832146/62f828b7-3598-4780-ae67-ffd4b6333366)
![image](https://github.com/dojoengine/dojo.js/assets/6832146/502b8ce5-196c-4eb8-a645-49b10a5f40be)

### What is the expected behavior?

successfully run and create the components

### Steps to reproduce

run the `pnpm create-components` after upgrading the dojo.js to `0.5.11-alpha.0`, get an error

downgrade the dojo.js to version `0.5.0`, run the same command, it works

### Trace

npm ERR! could not determine executable to run

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by ponderingdemocritus** [comment]
closing as this is on alpha build - just use stable release
