### ISSUE TITLE
[Feature]: Expose query clause to JS

### ISSUE THREAD

**Issue by RareSecond** [dojoengine/dojo.js#166]
### Feature Request

To support more expressive queries, we would need to expose the [`Clause`](https://github.com/dojoengine/dojo.js/blob/main/packages/torii-wasm/crate/src/lib.rs#L45) struct.

### Proposed Solution

The function should be able to convert queries like the one below to the necessary query that `torii-client` will understand.

```ts
const player = dojo_starter.findEntity([
    {
        model: "Moves",
        query: {
            player: account.account.address,
            OR: [
                { remaining: { gt: 50 } },
                { last_direction: Direction.Down },
            ],
        },
    },
    { model: "Position" },
] as const);
```

### Additional context

A bit more context can be found [in this RFC](https://github.com/dojoengine/dojo.js/pull/160) where a new API for interacting with your Dojo world is being discussed.

### If the feature is accepted, would you be willing to contribute it?

- [ ] Yes I would be willing to contribute

**Comment by EjembiEmmanuel** [comment]
@RareSecond I'd love to work on this if it is still open for contribution.

**Comment by Ugo-X** [comment]
@RareSecond please can i be assigned this task?
