### ISSUE TITLE
[Feature]: Adding PFP and Starknames using useStarkProfile on your frontend template

### ISSUE THREAD

**Issue by sdaav** [dojoengine/dojo.js#167]
### Feature Request

Hello!

It would be super cool to make the Starknet.id integration by adding .STARK domain and PFPs on your frontend template using our documentation.

Based on each repo we will adapt the method used (check all methods https://docs.starknet.id/)

You have several choices: 
- Starknetid.js
- Starknet React
- Starknet.js
- API 

Up to you to choose the best method for each repository, the best will be to use the library you are already using! 

@Marchand-Nicolas, one of our team members, can help to do it if needed!

### Proposed Solution

After connecting wallet, be able to see .STARK domain and PFP like on this example:

<img width="236" alt="Capture d’écran 2024-03-25 à 17 42 06" src="https://github.com/dojoengine/dojo.js/assets/57441909/ea26f09c-a5a5-4d9c-8818-0a0b4f3321da">

### If the feature is accepted, would you be willing to contribute it?

- [ ] Yes I would be willing to contribute

**Comment by ponderingdemocritus** [comment]
This is already implemented in starknet react, so not applicable to dojo.js

Closing for now

Feel free to do an example that uses Starknet.id, but we will not build it into the core.
