### ISSUE TITLE
[enhancement] Reconnect torii automatically 

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#200]
Torii currently disconnects after some time when connected to a client.

We need to handle a reconnection automatically within the library, so the user never experiences a drop off in sessions.

**Comment by Dprof-in-tech** [comment]
Hi @ponderingdemocritus , would love to work on this if it hasn't been already assigned.

**Comment by Ugo-X** [comment]
Good afternoon, my name is Ugo, a fullstack dev. I am positive i can handle this, please can i be assigned the issue?

**Comment by noyyyy** [comment]
gm, any update on this issue?
