### ISSUE TITLE
[Bug]: Model named Table breaks Torii sync

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo.js#204]
### Dojo.js Version

0.7.0-alpha.2

### What happened?

A model named `Table` raises an error on `getSyncEntities()`, preventing it to successfully sync:

```
failed to get entities: status: Internal, message: "error returned from database: (code: 1) near \"Table\": syntax error", details: [], metadata: MetadataMap { headers: {"content-length": "0", "content-type": "application/grpc-web+proto"} }
```

### What is the expected behavior?

The name of a model or field should not break Torii

### Steps to reproduce

* Create a model named 'Table' on dojo-starter
* Migrate
* Open some example that syncs using `getSyncEntities()` like `react-app`
* Monitor the console as the page loads, the error should be there.

Or use [this branch](https://github.com/underware-gg/pistols/tree/84674df1ddc6a6810b1b94fbcb0ec88279f80af8)
* Build and migrate on `/dojo`
* `pnpm run dev` on `/client`
* Open `http://localhost:3000/gate`
* Monitor the console as the page loads, the error should be there.

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by ponderingdemocritus** [comment]
Were you running torri alpha 7?

**Comment by ponderingdemocritus** [comment]
Fixing in new alpha - things changed in the torii build

**Comment by rsodre** [comment]
The problem persists on Dojo `0.7.0-alpha.5` and dojo.js `0.7.0-alpha.1`.
I can also see it on GraphQL Playground, should I open a dojo issue?
<img width="1069" alt="Screenshot 2024-06-06 at 18 01 46" src="https://github.com/dojoengine/dojo.js/assets/229161/c6eeb205-e605-44a1-9978-1a0e4ca0e777">

**Comment by ponderingdemocritus** [comment]
Is it only Table models that do not sync?

**Comment by rsodre** [comment]
`getSyncEntities()` fails, nothing syncs.

<img width="491" alt="Screenshot 2024-06-06 at 18 02 16" src="https://github.com/dojoengine/dojo.js/assets/229161/3b997f8d-c6ea-41cb-b392-a1872c03fe53">

**Comment by ponderingdemocritus** [comment]
This is a torii issue not wasm or client. Closing here.
