### ISSUE TITLE
[client] Update create-dojo to include non-react packages

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#205]
Currently create-dojo only supports the react packages, however it should also include the ability to install vue and node.

**Comment by Ugo-X** [comment]
Good afternoon, my name is Ugo, a fullstack dev. I am positive i can handle this, please can i be assigned the issue?

**Comment by LamsyA** [comment]
Hello @ponderingdemocritus , kindly assign this to me. I can work on it.

**Comment by LamsyA** [comment]
Hi @ponderingdemocritus, I would like to work on this issue, I am a fullstack blockchain developer, I have contributed to projects on the starknet ecosystem.
