### ISSUE TITLE
Dojo dev tooling

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#206]
Dojo.js deserves a dev tools package to allow developers to see what is happening across their dapp.

From experience, there are two major areas to monitor when building dapps:

Model updates: See what just changed.
Transaction information and tracking: See if there are any errors.

**Proposed Primitive**
Within Dojo core, we can emit the transaction (tx) data. These emitted events can then be consumed within a client in many ways. It is a generalized approach that allows any dapp downstream to access the data.

From this primitive data, we can build a Dojo dev tools package that listens for the events of the transactions (txs). The dev tools wouldn't be limited to this and could connect via graphql etc.

**Comment by devcollinss** [comment]
@ponderingdemocritus Can I be assigned? I will deliver it as soon as possible.

This are the steps i will take
1. Define requirements and scope.
2. Set up the development environment.
3. Implement model update monitoring.
4. Implement transaction tracking.
5. Build the dev tools interface.
6. Test and debug.
7. Document usage.

**Comment by Jonatan-Chaverri** [comment]
@ponderingdemocritus I'm not sure if someone has already implemented the changes in dojo core, but I can build an app to read the graphQL events and show them to the user in real time, show what has changed, show transaction details (reading the transactions query). Also maybe adding some buttons to automatically call the contracts (for this I will require the user to input the manifest). 

Is this what you want? I can show you a Figma design if you prefer.
