### ISSUE TITLE
[Feature]: Add support for event messages

### ISSUE THREAD

**Issue by Larkooo** [dojoengine/dojo.js#219]
### Feature Request

Expose the event messages bindings from dojo.c and integrate them into the SDK

- Retrieve event messages
- Subscribing to event message updates 

### Proposed Solution

Share the same logic, state management and subscription system as entities

### Related Code

https://github.com/dojoengine/dojo.c/blob/main/src/wasm/mod.rs#L747
https://github.com/dojoengine/dojo.c/blob/main/src/wasm/mod.rs#L907

### If the feature is accepted, would you be willing to contribute it?

- [ ] Yes I would be willing to contribute

**Comment by okhaimie-dev** [comment]
@Larkooo is anyone working on this?

**Comment by Larkooo** [comment]
> @Larkooo is anyone working on this?

Not that I know of, would you like to take over it?

**Comment by okhaimie-dev** [comment]
Yes! I'd love to work on it, but I cannot get started till next week. If that is okay, you can assign it to me

**Comment by Larkooo** [comment]
> Yes! I'd love to work on it, but I cannot get started till next week. If that is okay, you can assign it to me

Cool perfect, let me know if you have any questions. Event messages behave just like entities so it should follow the same structure and logic all around. Just different functions

**Comment by Larkooo** [comment]
@ponderingdemocritus if you could kindly assign this issue to @okhaimie-dev 🙏
