### ISSUE TITLE
[Bug]: Error accesing to Torii API from examples 

### ISSUE THREAD

**Issue by jorgezerpa** [dojoengine/dojo.js#240]
### Dojo.js Version

0.7.3

### What happened?

I followed along the steps of [Contributing to Dojo Guidelines](https://github.com/dojoengine/dojo.js?tab=readme-ov-file#contributing-to-dojojs). 

After finishing the installation steps, I tried to run the examples/react/react-app example following the [examples](https://github.com/dojoengine/dojo.js?tab=readme-ov-file#examples) guide. 

It seems to goes all good, but when I opened http://localhost:5173/ it displays just a white screen instead of the app. This because the call to setup function from main.tsx is falling -->
![image](https://github.com/user-attachments/assets/8da2f333-e5a7-4a03-8ac1-ffb30d3f0d50)

### Debugging
I opened the console and found this message:
```
http://0.0.0.0:8080/world.World/WorldMetadata net::ERR_ADDRESS_INVALID
```

After, I go to the examples/react/react-app/src/dojo/generated/setup.ts file, and harcode the value for toriiUrl passed to torii.createClient function. I hardcoded the value to "http://localhost:8080" instead of the "http://0.0.0.0/8080" url that is been taking from the config.toriiUrl prop.

This seems to be the solution, because after this I was able to run the example without any problem. 

Of course, hardcode the Torii url value is not the best practice. So I researched on the code and change the url on the next files:

* examples/node/torii-bot/.env.example
* examples/node/torii-bot/codegen.ts
* packages/core/src/constants/index.ts

But, despite that, when I ran the app again it still is using "0.0.0.0" instead of "localhost". **Maybe I have to rebuild something again to make the changes take effect?**

Looking on packages/core/src/constants/index.ts I found that LOCAL_KATANA variable is using localhost, so I think this is a suitable solution cause in the same file is the LOCAL_TORII variable (using 0.0.0.0) but again, I change it and not takes effect.  
 
 ps: I found this issue where the same function freeze the app, but it not seems to be related to this problem (https://github.com/dojoengine/dojo.js/issues/130)

### What is the expected behavior?

Shows the example application
 

### Steps to reproduce

* follow up the [Contributed to Dojo Guidelines](https://github.com/dojoengine/dojo.js?tab=readme-ov-file#contributing-to-dojojs) steps. 
* Try to run the examples/react/react-app
* When open the browser on port 5173, it shows a white screen instead of the app. 

### Trace

![image](https://github.com/user-attachments/assets/1d28d3e2-16d3-4f3c-a8e9-2274e8b2fcb0)

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by jorgezerpa** [comment]
If the solution is going the way I am, I would like to receive some feedback about my last question @ponderingdemocritus @tarrencev and be assigned to this same issue so I can fix it :)

**Comment by DIWAKARKASHYAP** [comment]
i want to work on this issue

**Comment by ponderingdemocritus** [comment]
This is fixed.
