### ISSUE TITLE
[burner] Remove options 

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#32]
Currently, the burner takes an options parameter in the set. This should be removed as it is not ideal if you want to use the hook in more than 1 place

```
    const { create, list, get, account, select, isDeploying, clear } = useBurner({
        masterAccount: masterAccount,
        accountClassHash: VITE_PUBLIC_ACCOUNT_CLASS_HASH!,
    });
 ```
 
 To:
 
 ```
    const { create, list, get, account, select, isDeploying, clear } = useBurner();
 ```
 
 This also means we need to pass the master account and class hash into the `create` function.

**Comment by Matth26** [comment]
I can take this one ser
