### ISSUE TITLE
[Feature]: Token balances subscription

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo.js#361]
### Feature Request

Provide a way to subscribe to new and changed token balances.

Depends on [dojo#2819](https://github.com/dojoengine/dojo/issues/2819)

### Proposed Solution

Add a function to the SDK package that subscribes to Torii token balances.

### Alternatives

Fetching all tokens periodically to apply changes, which is expensive.

### Related Code

This is how we fetch tokens. The subscription should return the same data:

https://github.com/dojoengine/dojo.js/blob/main/packages/sdk/src/index.ts#L192-L200

### If the feature is accepted, would you be willing to contribute it?

- [ ] Yes I would be willing to contribute

**Comment by MartianGreed** [comment]
This was added in [#v1.0.7](https://github.com/dojoengine/dojo.js/releases/tag/v1.0.7)

**Comment by rsodre** [comment]
> This was added in [#v1.0.7](https://github.com/dojoengine/dojo.js/releases/tag/v1.0.7)

unable to verify because of #354
