### ISSUE TITLE
[burner] Excessive rpc requests from useBurner() after burner manager initialization

### ISSUE THREAD

**Issue by Matth26** [dojoengine/dojo.js#41]
When invoking `useDojo()`, it internally calls `useBurner()`, which correctly fetches data from the storage. However, despite the Burner manager being previously initialized, `useBurner()` is still making unnecessary RPC requests.

Ideally, `useBurner()` should recognize when the Burner manager is already initialized and avoid making additional RPC calls.

**Comment by ponderingdemocritus** [comment]
Let's fix this - did you want to include the fix in the PR?

**Comment by Matth26** [comment]
Yes I'll do that
