### ISSUE TITLE
Support cairo u256 types

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo.js#62]
I currently rely on `u256` types on most of my models, and since Dojo js stack is not really supporting it yet, I am duplicating a lot of code on my projects, but it is a pain to maintain.
Yesterday I discovered that some of my contribution to that direction does not work anymore, so better formally issue it.

Probably everyone agrees that the best thing is to update the packages and actually support it, right?
I'm willing to do it.
Here's how I see it.
Just don't want to break anything else...

#### `@latticexyz/recs` vs. `@dojoengine/recs`

Is there anything really necessary in Dojo's fork of mud recs?
**Can't we just use Lattice's instead?**

Talking to @ponderingdemocritus a while back, I got the notion that there isn't really.
Since I needed mud 2.0 for `u256`, I replaced all my recs imports to mud, while Dojo was on mud 1.0.
But now that Dojo is broadly using mud 2.0, can't we just switch to `@latticexyz/recs`?
Everything was working fine.

Now I tried replacing my imports to dojo's fork and started getting all sorts of obscure problems, so got back to mud recs.

### Recs version with BigInt support

Because of mud 2.0 recs, I added this to [generateComponents.cjs](https://github.com/dojoengine/dojo.js/blob/main/packages/core/bin/generateComponents.cjs#L32)

```
// Extract recs package version
const { dependencies } = require(path.resolve("./package.json"));
const recsVersion = dependencies?.["@dojoengine/recs"] ?? "";
const isRecsVersion2 = /^[\^\~]?2./g.exec(recsVersion) != null;
console.log(
    `...generating for @dojoengine/recs version ${
        isRecsVersion2
            ? "2 (bigint support, Entity as string)"
            : "1 (no bigint, EntityIndex as number)"
    }`
)
```

This is now broken because the version check is looking in dojo's recs, not lattice's...

So I propose to remove the recs version check and just use mud 2.0 as default, with BigInt support.
OK?

### Recs types

Just saying that a `u256` is a `RecsType.BigInt` is not enough.
One `u256` is actually two `u128` in cairo, using two slots of event data.
Because of that... I added the `types` field on the generated metadata, so I can type check when parsing event data.

My models are looking like this on [contractComponents.ts](https://github.com/funDAOmental/lootunderworld/blob/main/client/src/dojo/contractComponents.ts):

```
      return defineComponent(
        world,
        {
          seed: RecsType.BigInt,
          minter: RecsType.BigInt,
          domain_id: RecsType.Number,
          token_id: RecsType.Number,
          yonder: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["u256","ContractAddress","u16","u16","u16"],
          },
        }
      );
```

But I just dicovered that my `types` were hijacked!
It is not storing cairo types anymore, instead, only custom types.
@kariy, is that the purpose or you just adapted to the new parser?
Adding all primitive tyes as well will fix this for me.

### Event data to components...

Now that I know which model fields are `u256`, [decodeComponent()](https://github.com/dojoengine/dojo.js/blob/f5cc9817b3b75c48c29bf117d95d7f3e7d2fcbf6/packages/utils/src/utils/index.ts#L114) has to be updated to consume two values from the event data when a `u256` pops up...

```
export function decodeComponent(
    schema: any,
    values: string[],
    valuesIndex: number
): any {
    // Iterate through the keys of the schema and reduce them to build the decoded component.
    return Object.keys(schema).reduce((acc: any, key) => {
        // If the current schema key points to an object and doesn't have a 'type' property,
        // it means it's a nested component. Therefore, we recursively decode it.
        if (typeof schema[key] === "object" && !schema[key].type) {
            acc[key] = decodeComponent(schema[key], values, valuesIndex);
        } else {
            // If the schema key points directly to a type or is not an object,
            // we parse its value using the provided parseComponentValue function
            // and move to the next index in the values array.
            acc[key] = parseComponentValue(values[valuesIndex], schema[key]);
            valuesIndex++;
        }
        return acc;
    }, {});
}
```

### npx core

Makes no sense to me that we use this command to generate the components file:

`npx @dojoengine/core xxx/manifest.json yyy/contractComponents.ts`

EDIT: nevermind, now that I understand better how it works, I see it is correct.

### Unit tests

I have NO idea on how to add unit tests to keep these things working forever.
I'll leave that to someone else to do the base implementation.
Just an idea...

**Comment by ponderingdemocritus** [comment]
ok lot to unpack!

We forked recs so custom nested types would work, sorry if this broke your projects! There is a PR open for this into the main recs so hopefully that will get merged soon. The only difference is that, however, it does mean you have to use dojoengine/recs for everything like the react package.

**bin**
We have to call the bin with npx like that so it is exposed via npm. This is how rollyourown also does it. Is that what you mean?

**Comment by rsodre** [comment]
Oh, in this case, I will try to get around using the dojo recs.

`bin`: roll your own calls scripts by name instead of *default* script.
This will only a matter of organization, only really required if we add more scripts to core.
But today it looks like the purpose of core is to generate the components file.

```
  "scripts": {
    "gen:models": "npx create-models ./manifest.json ./src/dojo/generated/contractModels.ts",
    "gen:events": "npx create-events ./manifest.json ./src/dojo/generated/contractEvents.ts"
  },
  "bin": {
    "create-models": "./bin/generateModels.cjs",
    "create-events": "./bin/generateEvents.cjs"
  },
```

Won't be able to start that today as I expected.
I need bun and all installs, and now at the airport...

**Comment by rsodre** [comment]
I've been trying to implement this, but every solution feels like a hack. I can keep using the original types in metadata that I proposed, but changes cascade a lot, it's getting ugly.

Now I think the best approach is to create new types on `@dojoengine/recs` for u256 types, because in fact, it is actually a different weird Cairo type. Not really a primitive, it contains two u128 fields. We just need to differentiate it from other BigInt types (u128, felt252, ContractAddress) so it will consume two event data values.

The new types would be:

- BigInt256,
- OptionalBigInt256,
- BigInt256Array,
- OptionalBigInt256Array,

With new types, it will be very simple to adapt the react packages in `decodeComponent()`.

Another solution would be to treat `u256` like a struct because in Cairo it is actually `{ low: u128, high: u128 }`. But on JS, it is always one BigInt, will probably break compatibility with torii and create some other problems on the client side.

@ponderingdemocritus , what do you think?
