### ISSUE TITLE
[core] add logging

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#72]
A parameter should be able to be passed into the RPCProvider which enables the logging of the provider actions.

**Comment by cpp-phoenix** [comment]
I have good experience with logging libraries. Please assign it to me @ponderingdemocritus

**Comment by ponderingdemocritus** [comment]
@cpp-phoenix great!

**Comment by ponderingdemocritus** [comment]
how are you going on this @cpp-phoenix ?

**Comment by cpp-phoenix** [comment]
Hey @ponderingdemocritus, A parameter should be added in the constructor of DojoProvider.ts in packages/core/src/provider/. Which should enable or disable the logging of provider methods. Is my understanding correct?

**Comment by ponderingdemocritus** [comment]
yes this is correct - and anything else you think
