### ISSUE TITLE
create wasm noise

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#74]
We currently have a js implementation of simplex, but it is not very fast.

https://github.com/dojoengine/dojo.js/blob/main/packages/utils/src/game/simplex.ts

This task is to convert this into WASM, which will be significantly faster.

FYI - this pairs with the onchain simplex noise in the cubit cairo lib.

**Comment by julienbrs** [comment]
Hi, can I take this one @ponderingdemocritus please?
