### ISSUE TITLE
[examples] Vite PWA 

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#80]
We need a very bare bones example of a dojo.js PWA.

Vite has great support for this - https://vite-pwa-org.netlify.app/

This should be fairly straight forward and should be based off the existing react-app, but just extended with the PWA features.

**Comment by ponderingdemocritus** [comment]
sure thing @satyambnsal ! It can really be an extension of the react-app

**Comment by ponderingdemocritus** [comment]
@satyambnsal how are you going on this?

**Comment by satyambnsal** [comment]
its done. Apologies for the delayed reply 🙏
