### ISSUE TITLE
[dojo.js] Testing suite CI

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#81]
```[tasklist]
### Tasks
- [ ] Generate components
- [ ] Test RPC
- [x] npx commands
- [ ] Burner tests
- [ ] Core package tests
```

**Comment by cpp-phoenix** [comment]
I can work on it @ponderingdemocritus

**Comment by ponderingdemocritus** [comment]
@cpp-phoenix have you started this? I was going to split this

**Comment by cpp-phoenix** [comment]
I am working on it. If you want you can split the tasks and assign them to me. I'll split my work in different PRs.
